org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod
mod.id=nomansland
mod.name=No Man's Land
mod.version=1.5.2
mod.group=com.farcr.nomansland
mod.license=All Rights Reserved
mod.authors=Farcr, Tazer, and many Contributors
mod.description=A vanilla-friendly overhaul that improves your Overworld, enhancing biomes and adding new ones alike - transforming the world with _great care to detail_ in every one of its aspects. From the tallest mountain peaks to the deepest of oceanic trenches, No Man's Land seeks to bring every single environment to the same level of quality and care. This mod is, at its core, supposed to enhance your Gameplay, and as such has all of its features designed to be greatly interactive and allowing of creative freedom. Everything in creation is blessed by beauty, and You are an inseparable part of it. So explore, and love as this world loves you.

# Minecraft
mc.version=1.21.1
mc.versionRange=[1.21.1]

# NeoForge - https://projects.neoforged.net/neoforged/neoforge
neo.version=21.1.227
neo.versionRange=[21.1.207,)
neo.loaderVersionRange=[4,)

# Parchment
parchment.mappingsVersion=2024.11.17
parchment.minecraftVersion=1.21.1

# Dependencies
deps.biolith=3.0.11
deps.biolith_range=[3.0.9,)
deps.mixed_litter=1.1.0
deps.mixed_litter_range=[1.1.0,)
deps.sable_companion=1.4.2
deps.sable_companion_range=[1.1.0,)
deps.create=6.0.9-215
deps.distant_horizons = 3.0.3-b
deps.jei=19.27.0.340